### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by MonoAdrian23** [hamid0740/JobUI#1]
Please add disable worlds Support.
You can Cheat Money in unbreakable zones.
Thank you

**Comment by hamid0740** [comment]
It actually works
You can check [here](https://github.com/hamid0740/jobui#how-to-let-players-use-job-command-and-earn-money-only-in-a-specified-world) to learn how to do this. 
Thanks for using my plugin

**Comment by MonoAdrian23** [comment]
Oh Shit sorry for my to stupid comment i havent read it.
I was to Lucky about plugin.
Sorry for my english greetings from Germany

Thanks for youre hard work

**Comment by hamid0740** [comment]
Thanks a lot
And don't forget to introduce my plugin to your friends
New features are coming soon
And a new release will be available in a few minutes
