### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by mrpwes** [hamid0740/JobUI#2]
Time need before they can get job again after retire.
I think this big use.

Have a nice day. Stay safe ❤️

**Comment by hamid0740** [comment]
Thanks for your suggestion
But you know if I want to add this feature, I need to add another file in config files
So I think I may not add this feature...

OR MAYBE YES??????

**Comment by mrpwes** [comment]
its up to you 

also you can add more feature like this job.yml

mode: SimpleMode
#SimpleMode or GoalMode
BlockID:BlockData:JobType: Money
#TheDefaultOne
1:0:Break:40
#GoalModeFormat
#BlockID:BlockData:JobType:Goal:Money
#1:0:Break:50:2000
#You Need to break 50 46:0 to claim 2000

Just an idea. hehe

**Comment by hamid0740** [comment]
Nice idea
But as you know each job can be a combination of 2 or more JobTypes
Actually I was just thinking about the GoalMode and SimpleMode, but I remembered that any job can be a combination of 2 or more JobTypes

But later I will absolutley add GoalMode Jobs

BTW I'm adding the Hunter and Murderer Job Types and will be available soon
