### ISSUE TITLE
MyJob Info does not show information

### ISSUE THREAD

**Issue by UnEnanoMas** [hamid0740/JobUI#4]
MyJob Info does not show information about anything even if you are in a job (Example: Tree cuter)

**Comment by hamid0740** [comment]
It should show
It doesn't have a problem for me

**Comment by hamid0740** [comment]
@UnEnanoMas 
I said that you need to remove the `plugin_data/JobUI` folder
Your problem may be because of this

**Comment by UnEnanoMas** [comment]
![image](https://user-images.githubusercontent.com/63286108/90313565-ddfaee00-df0d-11ea-9ce4-db5a1820269d.png)
Dont close the issue lol

**Comment by UnEnanoMas** [comment]
![image](https://user-images.githubusercontent.com/63286108/90313572-eeab6400-df0d-11ea-8b49-8f205052e801.png)
Dont close the issue lol

**Comment by UnEnanoMas** [comment]
![image](https://user-images.githubusercontent.com/63286108/90313581-fbc85300-df0d-11ea-81bd-00539668a824.png)

**Comment by UnEnanoMas** [comment]
I've already removed the plugin data, and it's still the same

**Comment by hamid0740** [comment]
Ok
I will check
And you can find the fixed version in v2.3.4

**Comment by hamid0740** [comment]
@UnEnanoMas 
Thanks for reporting the Bug

The Bug is now fixed in v2.3.4
