### ISSUE TITLE
No text to go back in MyJob Info

### ISSUE THREAD

**Issue by UnEnanoMas** [hamid0740/JobUI#6]
The go back button works perfectly, the only thing that the text does not appear

![image](https://user-images.githubusercontent.com/63286108/90334944-8faf2300-dfd1-11ea-99ea-394f558b99d7.png)

**Comment by hamid0740** [comment]
Umm
I will check and it will be fixed in v2.3.6

**Comment by hamid0740** [comment]
@UnEnanoMas 
This problem is not from my plugin
As I said before __If you have installed the plugin before, you need to remove `plugin_data/JobUI` Folder to let the new Yaml files get created.__

**Comment by hamid0740** [comment]
Hey @UnEnanoMas 

Sorry
You were right
The bug is fixed in v2.3.6
